/**
 * AOI IR DEFINES (auto generated)
 * generated by aoi_ir2java.aoi (http://kujirahand.com)
 */
package com.aoikujira.aoi2.compiler;

public class ANodeTypes {
  // IR code number
  public static final int NOP = 0;
  public static final int PUSH_NULL = 10;
  public static final int CONST_INT = 11;
  public static final int CONST_NUM = 12;
  public static final int CONST_STR = 13;
  public static final int LOAD = 14;
  public static final int LOAD_LOCAL = 15;
  public static final int GET_HASH = 16;
  public static final int STORE = 17;
  public static final int STORE_LOCAL = 18;
  public static final int LET = 19;
  public static final int POP = 20;
  public static final int ADD = 21;
  public static final int SUB = 22;
  public static final int MUL = 23;
  public static final int DIV = 24;
  public static final int MOD = 25;
  public static final int ADDSTR = 26;
  public static final int GT = 27;
  public static final int GTEQ = 28;
  public static final int LT = 29;
  public static final int LTEQ = 30;
  public static final int EQEQ = 31;
  public static final int NOTEQ = 32;
  public static final int NOT = 33;
  public static final int AND = 34;
  public static final int OR = 35;
  public static final int RET = 36;
  public static final int JUMP = 37;
  public static final int JUMP_ZERO = 38;
  public static final int JUMP_NON_ZERO = 39;
  public static final int CALL_USR = 40;
  public static final int CALL_LIB = 41;
  public static final int EXIT = 42;
  public static final int EOL = 43;
  public static final int POWER = 44;
  // IR code name
  public static final String[] names = {
    "NOP","","","","",
    "","","","","",
    "PUSH_NULL","CONST_INT","CONST_NUM","CONST_STR","LOAD",
    "LOAD_LOCAL","GET_HASH","STORE","STORE_LOCAL","LET",
    "POP","ADD","SUB","MUL","DIV",
    "MOD","ADDSTR","GT","GTEQ","LT",
    "LTEQ","EQEQ","NOTEQ","NOT","AND",
    "OR","RET","JUMP","JUMP_ZERO","JUMP_NON_ZERO",
    "CALL_USR","CALL_LIB","EXIT","EOL","POWER",
    };
  // arguments count
  public static final int[] args = {
    0,0,0,0,0,0,0,0,0,0,
    0,1,1,1,1,1,0,1,1,0,
    0,0,0,0,0,0,0,0,0,0,
    0,0,0,0,0,0,0,1,1,1,
    1,1,0,1,0,};
  // aoicode
  public static final String[] codes = {
    "_","","","","",
    "","","","","",
    "b","i","n","s","d",
    "D","h","t","T","=",
    "p","+","-","*","/",
    "%","&",">","G","<",
    "L","e","o","!","A",
    "O","r","J","Z","N",
    "u","l","q","~","w",
    };

}
